### ISSUE TITLE
(Just a appreciation-post)

### ISSUE THREAD

**Issue by loneicewolf** [d3npa/learning-kernelhacking#1]
## Hello!

First of all - sorry for making a `issue` (It's not a 'issue' but basically just a __Thank you__ word!)

### Thanks for making this repo!
So much effort and time must've been put into this. Why I make this issue is I just need to show my appreciation when I find something this useful, and clear(easy to read, etc).

Wishes from Sweden!
*This 'issue' may be closed*

Will.

**Comment by d3npa** [comment]
hej, tack!! jag var jätteglad att läsa denna när jag vaknade i morse 
(hope my duolingo swedish is ok.. i was really happy to wake up to this today!!)

**Comment by loneicewolf** [comment]
Hello! yea `:)` it was perfect, thought you was swedish at first 😆  heh, thanks! have a great day `^_^`
